blogproject/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^$',views.index),
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^cate/(?P<pk>[0-9]+)/$',views.CategoryView.as_view(),name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$',views.TagView.as_view(),name='tag'),
    url(r'^detail/(\d+)/$',views.detail,name='detail'),
]


# 关于正则表达式
# (?P<id>[0-9]+)与(\d+)

blogproject/blogproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls',namespace='blog')),
    url(r'^comments/',include('comments.urls')),
]

blogproject/comments/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(\d+)/$',views.comment)
]

blogproject/blog/models.py
from django.db import models
from django.contrib.auth.models import User


# 分类
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# 标签
class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# 文章
class Post(models.Model):

    # 文章标题
    title = models.CharField(max_length=70)

    # 配图
    pic = models.ImageField(upload_to='blog')

    # 文章正文
    body = models.TextField()

    # 创建时间
    created_time = models.DateTimeField()

    # 创建地址
    address = models.CharField(max_length=20)

    # 哪个作者
    author = models.ForeignKey(User)

    # 点赞数量
    like = models.IntegerField()

    # 不喜欢数量
    nolike = models.IntegerField()

    # 简介
    excerpt = models.CharField(max_length=200,blank=True)

    # 属于哪个分类
    category = models.ForeignKey(Category)

    # 属于什么标签
    tags = models.ManyToManyField(Tag,blank=True)

    def __str__(self):
        return self.title

blogproject/comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible


@python_2_unicode_compatible
class Comment(models.Model):

    # 评论用户的名字
    name = models.CharField(max_length=100)

    # 用户发表的内容
    text = models.TextField()

    # 属于哪一篇博客的评论
    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:10]

blogproject/blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post,Tag,Category
from comments.models import Comment
# 引入markdown模块
import markdown
# 引用类视图
from django.views.generic import ListView


# 详情
def detail(request,post_id):
    post = get_object_or_404(Post,id = int(post_id))
    post.body = markdown.markdown(post.body,
                                  extensions = [
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ])
    comment_all = Comment.objects.filter(post_id=post_id).order_by('-id')[:5]
    context = {'post':post,'comment_all':comment_all}
    return render(request,'blog/detail.html',context)


# 定义一个类，使其继承ＬistView
class IndexView(ListView):
    # 即将渲染的模板
    template_name = 'blog/index.html'
    # 指定获取的模型列表保存的变量名，遮盖变量会跟下面生成的context一同传递给模板
    context_object_name = 'post_all'
    # 指定每页显示的数据数量
    paginate_by = 1
    # 指明从哪个模型类获取数据
    def get_queryset(self):
        return Post.objects.order_by('-created_time')

    """
    在父类中有get_context_data()方法，在子类中重写该方法，
    同时为了在子类中使用父类中已经有的数据[paginator,page_obj,is_paginated]
    这是三个字典形式的模板变量，
    可以认为以上这三个数据是工厂的上游半成品，需要经过处理，再获取需要的产品
    然后又送回来，无论加工与否，出口都一样
    """

    def get_context_data(self, **kwargs):

        # 使用super()调用mro()列表中第一个父类的的get_context_data()方法
        # python3 super()不需要参数
        context = super().get_context_data()

        """
        paginator 是Paginator的一个实例，
        page_obj 是Page的一个实例，
        is_paginated 是一个布尔变量，用于指示是否已分页
        由于context是一个字典，所以调用get方法，从中取出某个键对应的值
        """
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        # 调用自己写的pagination_data()方法，获取显示分页导航条所需的数据
        pagination_data = self.pagination_data(paginator,page,is_paginated)

        # 将获取的分页导航条的模板变量更新到context中，注意pagination_data返回值也是一个字典
        context.update(pagination_data)

        # 将更新后的context返回，以便ListView使用字典中的模板变量取渲染模板
        # 这个时候context字典中已经有了显示分页的导航条所需的数据
        return context

    def pagination_data(self,paginator,page,is_paginated):
        if not is_paginated:
            # 如果没有分页，则无需分页导航条，不需要数据
            return {}

        # 当前页左边连续的页码号，初始值为空
        left = []

        # 当前页右边连续的页码号，初始值为空
        right = []

        # 标示第１页页码后是否需要显示省略号
        left_has_more = False

        # 标示最后一页前是否需要省略号
        right_has_more = False

        # 表示是否需要显示第一页
        # 因为如果当前页左边的连续页码中已经含有了第一页此时就不需要专门显示第一页了
        # 其他情况需要专门显示第一页
        # 默认值为Ｆalse
        first = False

        # 与上类似
        last = False

        page_number = page.number

        total_pages = paginator.num_pages

        page_range = paginator.page_range

        if page_number == 1:
            right = page_range[page_number:page_number + 2]

            if right[-1] < total_pages - 1:
                right_has_more = True

            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            if left[0] > 2:
                left_has_more = True

            if left[0] > 1:
                first = True

        else:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

        data = {
            'left':left,
            'right':right,
            'left_has_more':left_has_more,
            'right_has_more':right_has_more,
            'first':first,
            'last':last,
        }

        return data


# 分类
# 继承IndexView类
class CategoryView(IndexView):

    # 仔细观察你会发现这里少了３行，继承了
    def get_queryset(self):
        category = get_object_or_404(Category,pk=self.kwargs.get('pk'))
        return super().get_queryset().filter(category=category)


# 标签
class TagView(IndexView):

    def get_queryset(self):
        tag = get_object_or_404(Tag,pk=self.kwargs.get('pk'))
        return super().get_queryset().filter(tags=tag)

blogproject/comments/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from comments.models import Comment

def comment(request,post_id):
    post_id = int(post_id)
    post0 = request.POST
    name = post0['name']
    text = post0['comment']
    com = Comment()
    com.name = name
    com.text = text
    com.post_id = post_id
    com.save()
    return HttpResponseRedirect(reverse('blog:detail', args=(post_id,)))

blogproject/templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <title>Bootstrap Free Blog Template</title>
    <!-- BOOTSTRAP CORE STYLE CSS -->
    <link href="/static/css/bootstrap.css" rel="stylesheet" />
    <!-- FONTAWESOME STYLE CSS -->
    <link href="/static/css/font-awesome.css" rel="stylesheet" />
    <!-- CUSTOM STYLE CSS -->
    <link href="/static/css/style.css" rel="stylesheet" />
{#    <link href="/static/css/highlights/github.css" rel="stylesheet" />#}

    <link href="{% static 'css/highlights/github.css' %}" rel="stylesheet" />


</head>
<body>


    <section class="header-section">
        <div class="container">
            <div class="row">
                <div class="col-md-2">
                    <img src="/static/img/person.jpg" class="img-circle img-responsive" />
                </div>
                <div class="col-md-5 text-center">
                    <h1><strong>张武强</strong></h1>
                    <h4>一个不务正业的现代化人</h4>
                </div>
                <div class="col-md-5">
                    <h3>这哥们是谁？</h3>
                    一个26岁的男人.自从学习了python,就被她简介清爽，擅长分析的女神气质深深的吸引了
{#                    <i><strong>info@mydomain.com</strong></i>#}
                </div>
            </div>
        </div>
    </section>
    <!--HOME SECTION END-->

    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-2 spon-txt">
                    <span>我的赞助商</span>
                </div>
                <div class="col-md-10">
                    <img src="/static/img/clients.png" alt="" class="img-rounded img-responsive" />
                </div>


            </div>
        </div>
    </section>
    <!--SPONSORS SECTION END-->
    <hr />

    {% block body %}{% endblock %}
                <div class="col-md-3">
                    <ul class="list-group">
                        <li class="list-group-item"><strong>分类</strong></li>
                        {% get_categories as category_list %}
                        {% for cate in  category_list %}
                            <li class="list-group-item"><span class="badge">{{ cate.post_set.all.count }}</span><a
                                    href="/blog/cate/{{ cate.id }}/">{{ cate.name }}</a></li>
                        {% endfor %}
                        <li class="list-group-item"><strong>标签</strong></li>
                        {% get_tags as tag_list %}
                        {% for tag in tag_list %}
                            <li class="list-group-item"><a href="/blog/tag/{{ tag.id }}/">{{ tag.name }}</a></li>
                        {% endfor %}
                    </ul>
                    <br />

                    <ul class="list-group">
                        <li class="list-group-item"><strong>广告</strong>
                        </li>
                        <li class="list-group-item">
                            <a href="#">
                                <img src="/static/img/ad1.jpg" class="img-responsive" />
                            </a>
                            <br />
                            <a href="#">
                                <img src="/static/img/ad2.jpg" class="img-responsive" />
                            </a>
                        </li>
                    </ul>

                    <br/>
                </div>
            </div>
        </div>
    </section>
    <hr />
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center set-foot">
                &copy 2014 jhon alexan |  More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a>
            </div>
        </div>
    </div>

</body>
</html>

blogproject/templates/blog/detail.html
{% extends 'base.html' %}
{% block body %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-9" >
                      <div class="blog-main">
                        <div class="heading-blog">
                            {{ post.title }}
                        </div>
                        <img src="/static/{{ post.pic }}" class="img-responsive img-rounded" />
                        <div class="blog-info">
                            <span class="label label-primary">{{ post.created_time }}</span>
                            <span class="label label-success">{{ post.address }}</span>
                            <span class="label label-danger">{{ post.author }}</span>
                            <span class="label label-info">
                                <i class="fa fa-thumbs-up"></i>+ {{ post.like }}
                        <i class="fa fa-thumbs-down"></i>-{{ post.nolike }}
                            </span>
                        </div>
                        <div class="blog-txt">
                            {{ post.body|safe }}
                        </div>
                    </div>
                     <!--BLOG MAIN SECTION END-->
                    <h3><strong>发表评论</strong></h3>
                    <form action="/comments/{{ post.id }}/" method="post" class="comment-form">
                        <div class="row">
                            <div class="col-md-12">
                                <label for="id_name">名字：</label><br>
                                <input type="text" id="id_name" name="name" required>
                            </div>
                            <div class="col-md-12">
                                <label for="id_comment">评论：</label><br>
                                <textarea name="comment" id="id_comment" style="width:100%; height:100px"></textarea>
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <h3 ><strong>最近的评论</strong></h3>
                    <hr />
                    <ul class="media-list">
                        {% for comment in comment_all %}
                        <li class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object img-circle"   src="/static/img/user2.png" />
                            </a>
                            <div class="media-body">
                                <h4 class="media-heading">{{ comment.name }}</h4>
                                <p>{{ comment.text }}</p>
                            </div>
                        </li>
                        {% endfor %}
                   <!-- COMMENT SECTION - ONE END-->
                    </ul>
                     <!--COMMENTS SECTION END-->
                    </div>

{% endblock %}

blogproject/templates/blog/index.html
{% extends 'base.html' %}
{% block body %}
   <section>
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    {% for post in post_all %}
                    <div class="blog-main">
                        <div class="heading-blog">
                            {{ post.title }}
                        </div>
                        <a href="/blog/detail/{{ post.id }}/">
                            <img src="/static/{{ post.pic }}" class="img-responsive img-rounded" />
                        </a>
                        <div class="blog-info">
                            <span class="label label-primary">{{ post.created_time }}</span>
                            <span class="label label-success">{{ post.address }}</span>
                            <span class="label label-danger">{{ post.author }}</span>
                            <span class="label label-info">
                                <i class="fa fa-thumbs-up"></i>+{{ post.like }}
                        <i class="fa fa-thumbs-down"></i>-{{ post.nolike }}
                            </span>
                        </div>
                        <div class="blog-txt">
                            {{ post.excerpt }}
                        </div>
                    </div>
                    {% endfor %}
                    <!--BLOG ONE END -->
                    <nav>
                        {% if is_paginated %}
                        <ul class="pagination">
                            <li class="disabled"><a href="#"><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a></li>
                            {% if first %}
                                <li class="active"><a href="?page=1">1 <span class="sr-only"></span></a></li>
                            {% endif %}
                            {% if left %}
                                {% if left_has_more %}
                                    <span>...</span>
                                {% endif %}
                                {% for i in left %}
                                    <li><a href="?page={{ i }}">{{ i }}<span class="sr-only"></span></a></li>
                                {% endfor %}
                            {% endif %}
                            <li><a href="?page={{ page_obj.number }}">{{ page_obj.number }}<span class="sr-only"></span></a></li>
                            {% if right %}
                                {% for i in right %}
                                    <li><a href="?page={{ i }}">{{ i }}<span class="sr-only"></span></a></li>
                                {% endfor %}
                                {% if right_has_more %}
                                    <span>...</span>
                                {% endif %}
                            {% endif %}
                            {% if last %}
                                <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}<span class="sr-only"></span></a></li>
                            {% endif %}
                            <li><a href="#"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a></li>
                        </ul>
                        {% endif %}
                    </nav>
                     <!--PAGING  END -->
                </div>
{% endblock %}